[package]
name = "kmer"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.33"
noodles = { version = "0.111.0", features = ["bed", "core", "fasta"] }
regex = "1.12.4"
rustc-hash = "2.1.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150", features = ["std"] }
