[package]
name = "varianth-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = { version = "1.9.1", features = ["alloc"] }
noodles = { version = "0.76.0", features = ["core"] }
